apiVersion: v1
kind: Service
metadata:
  name: swiggy-service
  labels:
    app: swiggy
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
  selector:
    app: swiggy

